receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
  otlp:
    endpoint: "http://apm-server:8200"
    insecure: true

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 100
    check_interval: 5s

service:
  pipelines:
    metrics:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - otlp
    traces:
      processors:
      - batch
      receivers:
      - otlp
      exporters:
      - otlp
      - jaeger
